apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
spec:
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: pma
        image: phpmyadmin_image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - 'pgrep telegraf && pgrep nginx'
          initialDelaySeconds: 5
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: pma-service
  annotations:
    metallb.universe.tf/allow-shared-ip: acharlas
spec:
  selector:
    app: pma
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
      nodePort: 5000